name: Run the tests
on: [push, pull_request]

jobs:
  runtest_task:
    name: Using NodeJS and Postgres 12
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install NodeJS 10
        uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Install PostgreSQL 12
        run: |
          sudo apt-get -y install postgresql-12
          sudo apt-get -y install postgresql-client-12
      - name: before_install
        run: |
          npm install -g @lhci/cli@0.3.x
          sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
          sudo pg_ctlcluster 12 main restart
      - name: before_script
        run: |
          npm install -g dotenv-cli
          npm install -g sequelize-cli
          npm install -g sequelize
          npm install -g pg
          npm install -g bluebird
          source config/test.env
          sudo -u postgres createdb ${PGDATABASE}
          echo Created ${PGDATABASE}
          sudo -u postgres psql -c "CREATE ROLE ${PGUSER} WITH LOGIN PASSWORD '${PGPASSWORD}'"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${PGDATABASE} to ${PGUSER};"
          yarn sequelize:test db:migrate
          yarn sequelize:test db:seed:all
          yarn workspace server db-import-tests:test -c ${IMPORT_ARIA_AT_TESTS_COMMIT_1}
          yarn workspace server db-import-tests:test -c ${IMPORT_ARIA_AT_TESTS_COMMIT_2}
      - name: script
        run: yarn test
